# Codecov configuration for Arketic platform
# https://docs.codecov.com/docs/codecov-yaml

coverage:
  # Overall coverage target
  target: 80%
  
  # Coverage status checks
  status:
    project:
      default:
        # Project-wide coverage requirements
        target: 80%
        threshold: 2%  # Allow 2% decrease
        base: auto
        
      # Critical components require higher coverage
      critical:
        target: 90%
        threshold: 1%
        paths:
          - "components/ui/"
          - "lib/auth"
          - "lib/security"
          - "lib/validation"
        
    patch:
      default:
        # New code coverage requirements
        target: 85%
        threshold: 5%
        base: auto
        
      # New critical code requires highest coverage
      critical:
        target: 95%
        threshold: 1%
        paths:
          - "components/ui/"
          - "lib/auth"
          - "lib/security"
          - "lib/validation"

  # Precision of coverage percentages
  precision: 2

  # Round coverage to nearest whole number
  round: nearest

  # Coverage range for color coding
  range:
    - 70..80  # Yellow
    - 80..100 # Green

# Comment settings for pull requests
comment:
  layout: "reach,diff,flags,tree,reach"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
  
  # Show file-level coverage in PR comments
  show_carryforward_flags: true

# Ignore files and directories
ignore:
  - "**/*.stories.*"
  - "**/*.config.*"
  - "**/mock/**"
  - "**/__mocks__/**"
  - "**/types/**"
  - "**/*.d.ts"
  - "coverage/**"
  - "test-results/**"
  - "playwright-report/**"
  - ".next/**"
  - "public/**"
  - "scripts/**"
  - "*.md"

# Flag settings for different test types
flags:
  unit:
    paths:
      - "components/"
      - "lib/"
      - "hooks/"
      - "app/"
    carryforward: false
    
  integration:
    paths:
      - "tests/integration/"
    carryforward: false
    
  e2e:
    paths:
      - "tests/e2e/"
    carryforward: false

# Notification settings
notify:
  # Disable email notifications
  email: false
  
  # GitHub status checks
  github_status:
    default:
      threshold: 2%
      
  # Slack notifications (if configured)
  slack:
    default:
      url: "secret:SLACK_WEBHOOK_URL"
      threshold: 5%
      message: "Coverage changed by {{change}}% for {{owner}}/{{repo}}"

# Profiling (for performance analysis)
profiling:
  precision: 2
  round: down