# Development overrides for docker-compose.yml
# This file is automatically loaded by docker-compose in development

services:
  # API Development Optimizations
  api:
    build:
      target: deps  # Use deps stage for faster rebuilds in development
    command: python -m uvicorn main:app --host 0.0.0.0 --port 8000 --reload --log-level debug
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - WATCHFILES_FORCE_POLLING=true  # For file watching in containers
    stdin_open: true
    tty: true
    
  # Web Development Optimizations  
  web:
    build:
      target: deps  # Use deps stage for faster rebuilds
    command: npm run dev
    environment:
      - CHOKIDAR_USEPOLLING=true  # For file watching in containers
      - WATCHPACK_POLLING=true
      - FAST_REFRESH=true
    stdin_open: true
    tty: true
    
  # Enhanced Nginx for development
  nginx:
    volumes:
      - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx/conf.d