"""Add people table

Revision ID: 460f43e1b2ac
Revises: 003_add_auth_tokens
Create Date: 2025-08-07 13:22:17.831357

"""
from alembic import op
import sqlalchemy as sa
from core.types import UUID


# revision identifiers, used by Alembic.
revision = '460f43e1b2ac'
down_revision = '003_add_auth_tokens'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.Column('organization_id', UUID(as_uuid=True), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('job_title', sa.String(length=200), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('site', sa.String(length=200), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('employee_id', sa.String(length=50), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'USER', 'MANAGER', 'VIEWER', name='personrole'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'PENDING', name='personstatus'), nullable=False),
    sa.Column('hire_date', sa.DateTime(), nullable=True),
    sa.Column('manager_id', UUID(as_uuid=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['people.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('employee_id')
    )
    op.create_index('idx_person_department', 'people', ['department'], unique=False)
    op.create_index('idx_person_email', 'people', ['email'], unique=False)
    op.create_index('idx_person_manager', 'people', ['manager_id'], unique=False)
    op.create_index('idx_person_org', 'people', ['organization_id'], unique=False)
    op.create_index('idx_person_status', 'people', ['status'], unique=False)
    op.drop_index('idx_message_chat_created', table_name='chat_messages')
    op.create_index('idx_message_chat_created', 'chat_messages', ['chat_id', 'created_at', 'is_deleted'], unique=False)
    op.drop_index('idx_message_sender', table_name='chat_messages')
    op.create_index('idx_message_sender', 'chat_messages', ['sender_id', 'created_at'], unique=False)
    op.create_index('idx_message_ai_model', 'chat_messages', ['ai_model_used'], unique=False)
    op.create_index('idx_message_chat_type', 'chat_messages', ['chat_id', 'message_type'], unique=False)
    op.create_index('idx_message_deleted', 'chat_messages', ['is_deleted'], unique=False)
    op.create_index('idx_message_reply', 'chat_messages', ['reply_to_id'], unique=False)
    op.drop_index('idx_participant_active', table_name='chat_participants')
    op.create_index('idx_participant_chat_active', 'chat_participants', ['chat_id', 'is_active'], unique=False)
    op.create_index('idx_participant_joined', 'chat_participants', ['joined_at'], unique=False)
    op.create_index('idx_participant_permissions', 'chat_participants', ['can_send_messages', 'can_upload_files'], unique=False)
    op.create_index('idx_participant_user_active', 'chat_participants', ['user_id', 'is_active'], unique=False)
    op.drop_index('idx_chat_activity', table_name='chats')
    op.create_index('idx_chat_activity', 'chats', ['last_activity_at', 'is_archived'], unique=False)
    op.create_index('idx_chat_ai_model', 'chats', ['ai_model'], unique=False)
    op.create_index('idx_chat_created_at', 'chats', ['created_at'], unique=False)
    op.create_index('idx_chat_private', 'chats', ['is_private'], unique=False)
    op.drop_constraint('email_verification_tokens_token_hash_key', 'email_verification_tokens', type_='unique')
    op.drop_index('idx_email_verification_token_hash', table_name='email_verification_tokens')
    op.create_index(op.f('ix_email_verification_tokens_token_hash'), 'email_verification_tokens', ['token_hash'], unique=True)
    op.drop_constraint('organizations_slug_key', 'organizations', type_='unique')
    op.drop_index('ix_organizations_slug', table_name='organizations')
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.drop_index('idx_password_reset_token_hash', table_name='password_reset_tokens')
    op.drop_constraint('password_reset_tokens_token_hash_key', 'password_reset_tokens', type_='unique')
    op.create_index(op.f('ix_password_reset_tokens_token_hash'), 'password_reset_tokens', ['token_hash'], unique=True)
    op.drop_index('idx_refresh_token_hash', table_name='refresh_tokens')
    op.drop_constraint('refresh_tokens_token_hash_key', 'refresh_tokens', type_='unique')
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_index('ix_users_username', table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.create_unique_constraint('refresh_tokens_token_hash_key', 'refresh_tokens', ['token_hash'])
    op.create_index('idx_refresh_token_hash', 'refresh_tokens', ['token_hash'], unique=False)
    op.drop_index(op.f('ix_password_reset_tokens_token_hash'), table_name='password_reset_tokens')
    op.create_unique_constraint('password_reset_tokens_token_hash_key', 'password_reset_tokens', ['token_hash'])
    op.create_index('idx_password_reset_token_hash', 'password_reset_tokens', ['token_hash'], unique=False)
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.create_index('ix_organizations_slug', 'organizations', ['slug'], unique=False)
    op.create_unique_constraint('organizations_slug_key', 'organizations', ['slug'])
    op.drop_index(op.f('ix_email_verification_tokens_token_hash'), table_name='email_verification_tokens')
    op.create_index('idx_email_verification_token_hash', 'email_verification_tokens', ['token_hash'], unique=False)
    op.create_unique_constraint('email_verification_tokens_token_hash_key', 'email_verification_tokens', ['token_hash'])
    op.drop_index('idx_chat_private', table_name='chats')
    op.drop_index('idx_chat_created_at', table_name='chats')
    op.drop_index('idx_chat_ai_model', table_name='chats')
    op.drop_index('idx_chat_activity', table_name='chats')
    op.create_index('idx_chat_activity', 'chats', ['last_activity_at'], unique=False)
    op.drop_index('idx_participant_user_active', table_name='chat_participants')
    op.drop_index('idx_participant_permissions', table_name='chat_participants')
    op.drop_index('idx_participant_joined', table_name='chat_participants')
    op.drop_index('idx_participant_chat_active', table_name='chat_participants')
    op.create_index('idx_participant_active', 'chat_participants', ['is_active'], unique=False)
    op.drop_index('idx_message_reply', table_name='chat_messages')
    op.drop_index('idx_message_deleted', table_name='chat_messages')
    op.drop_index('idx_message_chat_type', table_name='chat_messages')
    op.drop_index('idx_message_ai_model', table_name='chat_messages')
    op.drop_index('idx_message_sender', table_name='chat_messages')
    op.create_index('idx_message_sender', 'chat_messages', ['sender_id'], unique=False)
    op.drop_index('idx_message_chat_created', table_name='chat_messages')
    op.create_index('idx_message_chat_created', 'chat_messages', ['chat_id', 'created_at'], unique=False)
    op.drop_index('idx_person_status', table_name='people')
    op.drop_index('idx_person_org', table_name='people')
    op.drop_index('idx_person_manager', table_name='people')
    op.drop_index('idx_person_email', table_name='people')
    op.drop_index('idx_person_department', table_name='people')
    op.drop_table('people')
    # ### end Alembic commands ###